config/routes.rb
Rails.application.routes.draw do 
  get 'welcome/index'

  resources :articles
  post '/articles/new' => 'articles#create'

  get 'register', to: 'users#new'
  resources :users, expect: [:new]
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#delete'

  resources :categories

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :text, presence: true, length: { minimum: 10, maximum: 600 }
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    if params.key? :month_year
      date = Date.strptime(params[:month_year], "%B,%Y")
      date_range = date.beginning_of_month..date.end_of_month
      @articles = Article
                    .where(created_at: date_range)
                    .order(:created_at)
                    .reverse_order
                    .paginate(page: params[:page], per_page: 5)
    else
      @articles = Article
                    .order(:created_at)
                    .reverse_order
                    .paginate(page: params[:page], per_page: 5)
    end
    @archives = Article
                  .group_by_month(:created_at)
                  .order(:created_at)
                  .reverse_order
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    redirect_back fallback_location: root_path
  end
private
  def article_params
    return params.require(:article).permit(:title, :text, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You do not have permission to modify this article"
      redirect_to @article
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% articles.each do |article| %>
  <div class="blog-post">
    <h2 class="blog-post-title">
      <%= article.title %>
    </h2>
    <% if article.categories.any? %>
      <div>
        <%= render article.categories %>
      </div>
    <% end %>
    <p class="blog-post-meta">
      <%= article.created_at.strftime("%B %e, %Y") %>
      by <%= link_to article.user.username, user_path(article.user) %>
    </p>

    <p>
    <% if logged_in? && 
        (article.user == current_user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Delete', 
                      article_path(article),
                      method: :delete, 
                      data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>

    <%= truncate_html(markdown(article.text), length: 280) %>
    <%= link_to 'Read More', article_path(article) %>
  </div>
<% end %> 

app/views/articles/_form.html.erb
<%= form_with model: article, local: true do |form| %>
  <%= render 'shared/errors', obj: article %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :text %> <br>
    <%= form.text_area :text, class: "form-control" %>
  </div>

  <div class"form-group">
    <%= form.label :category %>
    <%= form.collection_select :category_ids,
                                Category.all,
                                :id,
                                :name,
                                { prompt: "Empty" },
                                { multiple: true, 
                                  class:"form-control",
                                  size: 5 } %> 
  </div>

  <%= form.submit class: "btn btn-sm btn-outline-primary"%> 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-md-8 blog-main">
    <%= render 'article', articles: @articles %>
    <%= will_paginate @articles, renderer: custom_paginate_renderer, page_links: false  %>
  </div>
  <aside class="col-md-4 blog-sidebar">
    <div class="p-4 mb-3 bg-light rounded">
      <h4 class="font-italic">
        About
      </h4>
      <p class="mb-0">
        Saw you downtown singing the Blues. Watch you circle the drain. Why don't you let me stop by? Heavy is the head that <em>wears the crown</em>. Yes, we make angels cry, raining down on earth from up above.
      </p>
    </div>
    <div class="p-4">
      <h4 class="font-italic">Archives</h4>
      <ol class="list-unstyled mb-0">
        <% @archives.each do |archive| %>
          <li>
            <%= link_to archive.created_at.strftime("%B %Y"), month_year: archive.created_at.strftime("%B,%Y") %>
          </li>
        <% end %>
      </ol>
    </div>
    <div class="p-4">
      <h4 class="font-italic">Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </aside>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="col-md-12 blog-main">
  <div class="blog-post">
    <h2 class="blog-post-title">
      <%= @article.title %>
    </h2>
    <% if @article.categories.any? %>
      <div>
        <%= render @article.categories %>
      </div>
    <% end %>
    <p class="blog-post-meta">
      <%= @article.created_at.strftime("%B %e, %Y") %>
      by <%= link_to @article.user.username, user_path(@article.user) %>
    </p>
    

    <p>
      <%= link_to 'Show', article_path(@article) %>
      
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(@article) %>
        <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>

    <%= markdown(@article.text) %>
  </div>
</div>