config/routes.rb
Rails.application.routes.draw do 
  get 'welcome/index'

  resources :articles
  post '/articles/new' => 'articles#create'

  get 'register', to: 'users#new'
  resources :users, expect: [:new]
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#delete'

  resources :categories

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 16 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was been created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @articles = @category
                  .articles
                  .order(:created_at)
                  .reverse_order
                  .paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @category.update category_params
      flash[:notice] = "Category named updated"
      redirect_to @category
    end
  end

  def destroy
    @category.destroy
    redirect_to articles_path
  end

private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "You do not have admin permission"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, 
              category_path(category), 
              class: "badge badge-pill badge-info" %>

app/views/categories/_form.html.erb
<%= form_with model: category, local: true do |form| %>
  <%= render 'shared/errors', obj: category %>

  <div class="form-group">
    <%= form.label :name, "Category Name" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-sm btn-outline-primary"%> 
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <% if logged_in? && current_user.admin? %>
        <th scope="col" colspan="2"/>
      <% end %>
      <th scope="col" class="text-right">Count</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <th scope="row">
          <%= link_to category.name, category %>
        </th>
        <% if logged_in? && current_user.admin? %>
          <td class="text-center">
            <%= link_to "Edit", edit_category_path(category) %>
          </td>
          <td class="text-center">
            <%= link_to "Destroy", category, method: :delete, 
              data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
        <td class="text-right">
          <%= category.articles.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="col-md-12 blog-main">
  <div class="blog-post">
    <h2 class="text-center">
      <%= @category.name %>
    </h2>
    <% if logged_in? && current_user.admin? %>
      <div class="text-center">
        <%= link_to "Edit", edit_category_path(@category) %>
        <%= link_to "Destroy", @category, method: :delete, 
          data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= render 'articles/article', articles: @articles %>
    <%= will_paginate @articles, 
                        renderer: :custom_paginate_renderer,
                        page_links: false  %>
  </div>
</div>