config/routes.rb
Rails.application.routes.draw do 
  get 'welcome/index'

  resources :articles
  post '/articles/new' => 'articles#create'

  get 'register', to: 'users#new'
  resources :users, expect: [:new]
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#delete'

  resources :categories

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small special-color-dark pt-4">
  <div class="footer-copyright text-center py-3">
    <small>
      Copyright &copy; 
      <%= link_to "ezequias2d", "https://github.com/ezequias2d" %>
    </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert 
                  alert-<%= name == "notice" ? "success" : "danger" %>
                  alert-dismissible fade show fade show" role="alert">
      <%= msg %>
      <button 
              type="button" 
              class="close" 
              data-dismiss="alert" 
              aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1"> 
        <% if logged_in? %>
          <div class="dropdown">
            <a 
               class="text-muted dropdown-toggle" 
               href="#" 
               id="navbarDropdown" 
               role="button" 
               data-toggle="dropdown" 
               aria-haspopup="true" 
               aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %>
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", 
                            user_path(current_user), 
                            class: "dropdown-item" %>
              <%= link_to "Edit profile", 
                            edit_user_path(current_user),
                            class: "dropdown-item" %>
              <%= link_to "Delete profile",
                            user_path(current_user), 
                            class: "dropdown-item text-danger", 
                            method: :delete, 
                            data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        <% else %>
          <%= link_to "Register",
                        register_path, 
                        class: "btn btn-sm btn-outline-secondary" %>
        <% end %>
      </div> 
      <div class="col-4 text-center">
        <%= link_to "Blog", 
                      root_path,
                      class: "blog-header-logo text-dark"%>
      </div>
      <div class="col-4 d-flex justify-content-end 
                  align-items-center search-container">
        <form>
          <input class="search expandright" 
                 id="searchright"
                 type="search" 
                 name="q" 
                 placeholder="Search">
          <label class="text-muted" for="searchright">
            <svg xmlns="http://www.w3.org/2000/svg" 
                 width="20" 
                 height="20" 
                 fill="none" 
                 stroke="currentColor" 
                 stroke-linecap="round" 
                 stroke-linejoin="round" 
                 stroke-width="2" 
                 class="mx-3" 
                 role="img" 
                 viewBox="0 0 24 24" 
                 focusable="false">
              <title>Search</title>
              <circle cx="10.5" 
                      cy="10.5" 
                      r="7.5">
              </circle>
              <path d="M21 21l-5.2-5.2"></path>
            </svg>  
          </label>
        </form>

        <% if logged_in? %>
          <%= link_to "Sign out", 
                        signout_path, 
                        class: "btn btn-sm btn-outline-secondary", 
                        method: :delete %>
        <% else %>
          <%= link_to "Sign in", 
                        signin_path, 
                        class: "btn btn-sm btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <% Category.all.each do |category| %>
      <%= link_to category.name, 
                    category_path(category),
                    class: "p-2 text-muted" %>
    <% end %>
    <%= link_to "Bloggers", users_path, class: "p-2 text-muted" %>
    <%= link_to "Articles", articles_path, class: "p-2 text-muted" %>
    <% if logged_in? %>
    <div class="dropdown">
      <a 
          class="text-muted dropdown-toggle" 
          href="#" 
          id="navbarDropdown" 
          role="button" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
          ...
      </a>
      <div 
          class="dropdown-menu dropdown-menu-right"
          aria-labelledby="navbarDropdown">
        <% if current_user.admin? %>
          <%= link_to "New Category", 
                        new_category_path, 
                        class: "dropdown-item" %>
        <% end %>
        <%= link_to "View Categories",
                      categories_path,
                      class: "dropdown-item" %>     
        <%= link_to "New Article", 
                      new_article_path, 
                      class: "dropdown-item" %>
      </div>
    </div>
    <% end %>
  </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 
                              media: 'all', 
                              'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 
                              'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main role="main" class="container" id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html class="session-html">
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 
                              media: 'all', 
                              'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 
                              'data-turbolinks-track': 'reload' %>
  </head>

  <body class="session-body text-center"> 
      <%= yield %>
  </body>
</html>